name: Run test and linting for pylumi

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # - name: Install Go
      #   run: |
      #     sudo apt-get install -y golang
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Run tests
        run: |
          make test
