name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        python: [3.6, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.1
      - name: Install dependencies
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:~/.pulumi/bin

          pulumi plugin install resource aws 4.33.0

          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt -r requirements-dev.txt
          pip install .
      - name: Check Formatting
        run: |
          make check-fmt
      - name: Run tests
        run: |
          make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
