name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  test:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          curl -fsSL https://get.pulumi.com | sh
          pulumi plugin install resource aws 2.13.1

          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Run tests
        run: |
          make test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
